name: RSS to Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'  # 每8小时运行一次

jobs:
  send_rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # 或者你需要的其他版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 从 requirements.txt 安装依赖

      - name: Run Python scripts
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_YOUTUBE }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python send_rss.py
          python youtube_rss.py  # 运行第二个脚本
          
      - name: Commit sent entries
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'action@github.com'
          git add sent_entries.json
          if ! git diff --cached --quiet; then  # 检查是否有变化
            git commit -m 'Update sent entries'
            git push
          else
            echo "No changes to commit"
