name: RSS to Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'  # 每天晚上9点运行

jobs:
  send_rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests feedparser

    - name: Run send_rss.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python send_rss.py

    - name: Upload sent_entries.json
      if: always()  # 确保即使失败也上传
      uses: actions/upload-artifact@v3
      with:
        name: sent_entries
        path: sent_entries.json

    - name: Download sent_entries.json
      if: always()  # 确保即使失败也下载
      uses: actions/download-artifact@v3
      with:
        name: sent_entries
