name: RSS to Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'  # 每天晚上9点运行

jobs:
  fetch_rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # 自动下载上次的 sent_entries.json 文件
      - name: Download sent_entries.json artifact
        uses: actions/download-artifact@v3
        with:
          name: sent-entries
          path: ./  # 下载到当前工作目录

      - name: Run RSS fetch script
        run: |
          source venv/bin/activate
          python send_rss.py

      # 自动上传 sent_entries.json 文件
      - name: Upload sent_entries.json artifact
        uses: actions/upload-artifact@v3
        with:
          name: sent-entries
          path: sent_entries.json
