name: RSS to Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'  # 每8小时运行一次

jobs:
  send_rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 从 requirements.txt 安装依赖

      # 并行运行两个脚本，确保工作流继续进行
      - name: Run both scripts in parallel
        env:
          TELEGRAM_BOT_TOKEN_RSS: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN_YOUTUBE: ${{ secrets.TELEGRAM_BOT_YOUTUBE }}
        run: |
          python send_rss.py || echo "send_rss.py failed" &
          python youtube_rss.py || echo "youtube_rss.py failed" &
          wait  # 等待两个脚本执行完毕

      - name: Commit sent_entries.json
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'action@github.com'
          git add sent_entries.json
          if ! git diff --cached --quiet; then
            git commit -m 'Update sent_entries'
            git push
          else
            echo "No changes to commit"

      - name: Commit youtube_rss.json
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'action@github.com'
          git add youtube_rss.json
          if ! git diff --cached --quiet; then
            git commit -m 'Update youtube_rss'
            git push
          else
            echo "No changes to commit"
