name: RSS to Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'  # 每8小时运行一次

jobs:
  send_rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # 或者你需要的其他版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 从 requirements.txt 安装依赖

      - name: Run send_rss.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python send_rss.py

      - name: Run youtube_rss.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_YOUTUBE }}  # 可根据需要定义不同的变量
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python youtube_rss.py
          
      - name: Commit sent_entries.json
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'action@github.com'
          git add sent_entries.json
          if ! git diff --cached --quiet; then  # 检查是否有变化
            git commit -m 'Update sent_entries'
            git push
          else
            echo "No changes to commit"

      - name: Commit youtube_rss.json
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'action@github.com'
          git add youtube_rss.json
          if ! git diff --cached --quiet; then  # 检查是否有变化
            git commit -m 'Update youtube_rss'
            git push
          else
            echo "No changes to commit"

