name: RSS to Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # 每8小时运行一次

jobs:
  send_rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 并行运行两个脚本
      - name: Run both scripts in parallel
        env:
          TELEGRAM_BOT_TOKEN_RSS: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN_YOUTUBE: ${{ secrets.TELEGRAM_BOT_YOUTUBE }}
        run: |
          python send_rss.py || echo "send_rss.py failed" &
          python youtube_rss.py || echo "youtube_rss.py failed" &
          wait

      # 提交 sent_entries.json
      - name: Commit sent_entries.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sent_entries.json  # 暂存更改
          git commit -m "Update sent_entries.json with new sent emails" || echo "No changes to commit"
          git push origin main  # 直接推送而不拉取

      - name: Commit youtube_rss.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add youtube_rss.json  # 暂存更改
          git commit -m "Update youtube_rss.json with new sent emails" || echo "No changes to commit"
          git push origin main  # 直接推送而不拉取

        continue-on-error: true  # 允许此步骤出错
